import {CaretPosition, EditorFrameObjects, RootContainerFrameDefinition, ImportsContainerDefinition, FuncDefContainerDefinition, MainFramesContainerDefinition, getFrameDefType, AllFrameTypesIdentifier} from "@/types/types";

const initialFizzState: EditorFrameObjects = {
    0: {
        id: 0,
        frameType : RootContainerFrameDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [-1, -2, -3],
        jointParentId: 0,
        jointFrameIds: [],
        labelSlotsDict: { },
        caretVisibility: CaretPosition.none,
    },
    "-1": {
        id: -1,
        frameType : ImportsContainerDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        labelSlotsDict: {},
        isCollapsed: false,
        caretVisibility: CaretPosition.none,
    },
    "-2": {
        id: -2,
        frameType : FuncDefContainerDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [1],
        jointParentId: 0,
        jointFrameIds: [],
        labelSlotsDict: { },
        isCollapsed: false,
        caretVisibility: CaretPosition.none,
    },
    "-3": {
        id: -3,
        frameType : MainFramesContainerDefinition,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 0,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        labelSlotsDict: {},
        isCollapsed: false,
        caretVisibility: CaretPosition.body,
    },

    1: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.funcdef),
        id: 1,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: -2,
        childrenIds: [2,3,4,5],
        jointParentId: 0,
        jointFrameIds: [],
        labelSlotsDict: {
            0: {slotStructures: {operators: [], fields: [{code: "fizzbuzz"}]}},
            1: {slotStructures: {operators: [], fields: [{code: "num"}]}},
        },
        caretVisibility: CaretPosition.none,
    },

    2: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.varassign),
        id: 2,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 1,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        labelSlotsDict: {
            0: {slotStructures: {operators: [], fields: [{code: "arr"}]}},
            1: {slotStructures: {operators: [], fields: [{code: "[]"}]}},
        },
        caretVisibility: CaretPosition.none,
    },

    3: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.comment),
        id: 3,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 1,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        labelSlotsDict: {0: {slotStructures: {operators: [], fields: [{code: "Write your code here:"}]}}},
        caretVisibility: CaretPosition.none,
    },

    4: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.blank),
        id: 4,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 1,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        labelSlotsDict: {0: {slotStructures: {operators: [], fields: [{code: ""}]}}},
        caretVisibility: CaretPosition.none,
    },

    5: {
        frameType: getFrameDefType(AllFrameTypesIdentifier.return),
        id: 5,
        isDisabled: false,
        isSelected: false,
        isVisible: true,
        parentId: 1,
        childrenIds: [],
        jointParentId: 0,
        jointFrameIds: [],
        labelSlotsDict: {0: {slotStructures: {operators: [], fields: [{code: "arr"}]}}},
        caretVisibility: CaretPosition.none,
    },

};

export default initialFizzState;